# Generated by Django 4.0.4 on 2022-05-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_news_image_tags_image_alter_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='tags'),
        ),
    ]
