# Generated by Django 4.0.4 on 2022-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_tags_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
